### ISSUE TITLE
request multiple addresses at once when requesting from blockchain.info

### ISSUE THREAD

**Issue by ohadcn** [dan-v/bruteforce-bitcoin-brainwallet#7]
blockchain.info allows requesting balance for some addresses divided by | in one request.
since it takes a lot of time between requests, and usually most of the requests are for empty addresses, this might be useful.

the requests should look like that:
https://blockchain.info/q/getreceivedbyaddress/1XEcRiWpnNjyXw6tA76NDvSVa7D1sS23x|1HUBHMij46Hae75JPdWjeZ5Q7KaL7EFRSD

**Comment by yusuf** [comment]
For experimentation and educational purposes its better to do it offline, faster & no need for internet, but you got to download a lot...

Example Code
http://www.bitbin.it/wkrLIugi/
